{
  "hash": "37b581eaa42dd06eb38bc2912b695681",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supervised learning: generalized linear models\"\nauthor: \"<br>CMSACamp 2026<br><br>Department of Statistics & Data Science<br>Carnegie Mellon University\"\nfooter:  \"[36-SURE.github.io/2026](https://36-sure.github.io/2026)\"\nformat:\n  revealjs:\n    theme: theme.scss\n    chalkboard: true\n    smaller: true\n    slide-number: c/t\n    code-line-numbers: false\n    linestretch: 1.25\n    html-math-method:\n      method: mathjax\n      url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n\n\n# Background\n\n## Recap\n\n* When the response is continuous, we can use linear regression \n\n. . .\n\n* When the response is binary categorical, we can use logistic regression\n\n. . .\n\n* Which model do we use if the response contains discrete counts?\n\n## Generalized linear models (GLMs)\n\nThree components of a GLM\n\n. . .\n\n**1. Random component (distribution of the response)**\n\n*   Identifies the response variable and assumes a probability distribution for it\n\n. . .\n\n**2. Linear predictor**\n\n*   Specifies the predictor variables\n  \n*   Linear combination of predictors on the right-hand side of the model equation\n  \n*   In the form $\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$\n\n. . .\n\n**3. Link function (a function of the parameter)**\n\n* Connects a linear combination of predictor variables to the mean of the response variable's probability distribution\n\n## Linear regression\n\n1. $Y \\sim N(\\mu, \\sigma ^2)$\n\n. . .\n\n2. Linear predictor: $\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$\n\n. . .\n\n3. Identity link function: $g(\\mu) = \\mu$\n\n## Logistic regression\n\n1. $Y \\sim \\text{Binomial}(n,p)$\n\n. . .\n\n2. Linear predictor: $\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$\n\n(Recall: We cannot just simply model $p = \\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$ since the binary response can only take on values of either 0 or 1)\n\n. . .\n\n3. Logit link function: $\\displaystyle g(p) = \\log\\left(\\frac{p}{1-p}\\right)$\n\n$$\\log \\left( \\frac{p(x)}{1 - p(x)} \\right) = \\beta_0 + \\beta_1 x_1 + \\cdots + \\beta_p x_p$$\n\n$$\\frac{p(x)}{1 - p(x)} = \\exp(\\beta_0 + \\beta_1 x_1 + \\cdots + \\beta_p x_p) $$\n\n$$p(x) = \\frac{\\exp(\\beta_0 + \\beta_1 x_1 + \\cdots + \\beta_p x_p)}{1 + \\exp(\\beta_0 + \\beta_1 x_1 + \\cdots + \\beta_p x_p)} = \\frac{1}{1 + \\exp(-(\\beta_0 + \\beta_1 x_1 + \\cdots + \\beta_p x_p))}$$\n\n\n## Poisson regression\n\n1. $Y \\sim \\text{Poisson}(\\lambda)$ where $\\lambda = E[Y|X=x]$\n\n. . .\n\n2. Linear predictor: $\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$\n\n(We cannot just simply model $\\lambda = \\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$ since the Poisson mean parameter must be positive)\n\n. . .\n\n3. Log link function: $\\displaystyle g(\\lambda) = \\log (\\lambda)$\n\n$$\\log(\\lambda) =\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$$\n$$\\lambda = \\exp(\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p)$$\n\nwhich guarantees $\\lambda >0$.\n\n## Generalization example\n\nIn linear regression, the distribution is normal and the domain of $Y \\mid x$ is $(-\\infty,\\infty)$\n\n. . .\n\nWhat, however, happens if we know that\n\n* the domain of observed values of the response is actually $[0,\\infty]$\n\n* the observed values are __discrete__, with possible values $0, 1, 2, \\dots$\n\n. . .\n\n__The normal distribution doesn't hold here__\n\n- Which distribution could possibly govern $Y \\mid x$?\n\n- Remember, we might not know truly how $Y \\mid x$ is distributed, but any assumption we make has to fit with the nature of the data\n\n## Generalization: Poisson regression\n\n-   PMF of a Poisson distribution: $\\displaystyle f(x \\mid \\lambda)= \\frac{ e^{-\\lambda} \\lambda^x}{x!}$; $x = 0, 1, 2, \\dots$ and $\\lambda > 0$\n\n. . .\n\n- Model for the counts of an event in a fixed period of time or space, with a rate of occurrence (intensity) parameter $\\lambda$\n\n. . .\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n- $\\lambda$ is __both__ the mean and the variance of the distribution\n\n  - in general, the variance governs the distribution's shape\n\n- distribution of independent event occurrences in an interval, e.g. soccer goals in a match\n\n- $\\lambda$ is the average number of the events in an interval\n\nSo, when we apply GLM in this context, we would identify the family as Poisson\n\nBut there's another step in generalization...\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGhtN8PsfXb92k34HFNi14zpkCwpWRIBnY_1GkL1GsbKohpqSTNze-7XY&s=10){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n:::\n\n\n\n## Generalization: link function\n\nStart with one predictor, linear function: $\\beta_0 + \\beta_1 x$\n\n. . .\n\nRange of this function: $(-\\infty,\\infty)$\n\nBut for Poisson regression, $Y$ __cannot be negative__,\n\n__We need to transform the linear function__ to be $[0,\\infty)$ \n\n  (What if we use linear regression? Results may not be meaningful, e.g., we predict ${\\hat Y}$ to be negative!)\n\n. . .\n\n__There is usually no unique transformation__, but rather conventional ones\n\n## Generalization: link function\n\nFor Poisson, we use the $\\log()$ function as the __link function__ $g()$:\n\n$$g(\\lambda \\mid x) = \\log(\\lambda \\mid x) = \\beta_0 + \\beta_1 x$$\n\n\n(Hence we also call this a [log-linear model](https://en.wikipedia.org/wiki/Log-linear_model))\n\n. . .\n\nGiven $Y$ with values limited to being either 0 or positive integers, with no upper bound, we\n\n1. assume $Y \\mid x \\sim \\text{Poisson}(\\lambda)$\n\n2. assume $\\lambda \\mid x = e^{\\beta_0 + \\beta_1 x}$ \n\n3. use optimization to estimate $\\beta_0$ and $\\beta_1$ by maximizing the likelihood function\n\n\n## More distributions\n\n[Gamma distribution](https://en.wikipedia.org/wiki/Gamma_distribution)\n\n* $Y \\mid x$ continuous, but bounded between 0 and $\\infty$\n\n* Application: modeling continuous, positive, and (right) skewed response\n\n  * Finance: modeling insurance claim severity\n  \n  * Environmental science: modeling rainfall\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](https://careersatdoordash.com/wp-content/uploads/2022/04/gamma-distribution-11-1-1024x801.jpg){fig-align='center' width=50%}\n:::\n:::\n\n\n## More distributions\n\n[Beta distribution](https://en.wikipedia.org/wiki/Beta_distribution)\n\n* $Y \\mid x$ continuous, but bounded between 0 and 1\n\n* Application: modeling proportions (see [here](https://www.andrewheiss.com/blog/2021/11/08/beta-regression-guide) for an example)\n\n  * Amount of foreign aid a country receives as a percent of its GDP\n  \n  * Proportion of a population that received COVID-19 vaccine \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](https://miro.medium.com/v2/1*n1q2lm3-2Npx2AMCWUaYMQ.png){fig-align='center' width=50%}\n:::\n:::\n\n\n## Modeling count data\n\nGame level shot information for the NHL 2021-2022 season, via the [SCORE Sports Data Repository](https://data.scorenetwork.org/hockey/nhl-shots.html)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ntheme_set(theme_light())\nscoring <- read_csv(\"https://raw.githubusercontent.com/36-SURE/2026/main/data/nhl_offense_2021.csv\")\nglimpse(scoring)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,802\nColumns: 8\n$ game_id    <dbl> 2021020001, 2021020001, 2021020002, 2021020002, 2021020003,…\n$ event_team <chr> \"Pittsburgh Penguins\", \"Tampa Bay Lightning\", \"Seattle Krak…\n$ shots      <dbl> 58, 55, 63, 58, 55, 64, 53, 48, 61, 70, 67, 66, 58, 54, 68,…\n$ avg_dist   <dbl> 34.45106, 41.99500, 34.34091, 35.07234, 35.58780, 34.63137,…\n$ avg_angle  <dbl> 29.69149, 25.62750, 33.07727, 29.58298, 31.37805, 26.01373,…\n$ goals      <dbl> 6, 2, 3, 4, 1, 2, 1, 5, 2, 4, 2, 2, 5, 1, 3, 2, 6, 7, 5, 4,…\n$ is_home    <dbl> 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,…\n$ division   <chr> \"Metropolitan\", \"Atlantic\", \"Pacific\", \"Pacific\", \"Atlantic…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## EDA: Distribution for the number of goals\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nscoring |> \n  count(goals) |> \n  ggplot(aes(goals, n)) +\n  geom_col(width = 0.5) \n```\n\n::: {.cell-output-display}\n![](17-glm_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## EDA: Distribution for the number of goals by home/away team\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nscoring |> \n  count(goals, is_home) |> \n  mutate(is_home = factor(is_home)) |> \n  ggplot(aes(goals, n, fill = is_home, group = is_home)) +\n  geom_col(position = \"dodge\", width = 0.5)\n```\n\n::: {.cell-output-display}\n![](17-glm_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=1440}\n:::\n:::\n\n\n## EDA: Relationship between shot distance and goals\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na <- scoring |> \n  mutate(goals_group = case_when(goals <2 ~ \"0-1\", \n                                 goals >= 2 & goals <=3 ~ \"2-3\", \n                                 goals == 4 ~ \"4\", \n                                 goals > 4 ~ \"5+\")) |>\n  ggplot(aes(x=avg_dist, color = goals_group))+\n  geom_density()+\n  theme(legend.position = \"bottom\")\n\nb <- scoring |> \n  ggplot(aes(x=avg_dist, y = goals))+\n  geom_point(position = \"jitter\", alpha=0.5)+\n  geom_smooth()\n\nlibrary(patchwork)\na+b\n```\n:::\n\n\n:::\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-glm_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n:::\n\n## Fitting a poisson regression model\n\nWhat observations in the dataset correspond to predictions using only the intercept?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngoals_poisson <- glm(goals ~ division + is_home + avg_dist, family = \"poisson\", data = scoring)\n\n# summary(goals_poisson)\n# scoring <- scoring |> mutate(division = fct_relevel(division, \"Central\")) # use to change the reference level\n\nlibrary(broom)\ntidy(goals_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  term                 estimate std.error statistic  p.value\n  <chr>                   <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)            1.50     0.0874     17.1   8.04e-66\n2 divisionCentral        0.0132   0.0299      0.441 6.59e- 1\n3 divisionMetropolitan  -0.0229   0.0303     -0.756 4.50e- 1\n4 divisionPacific       -0.0367   0.0305     -1.20  2.29e- 1\n5 is_home                0.0819   0.0215      3.80  1.44e- 4\n6 avg_dist              -0.0112   0.00239    -4.68  2.88e- 6\n```\n\n\n:::\n:::\n\n\n## Fitting a poisson regression model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(goals_poisson, exponentiate = TRUE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  term                 estimate std.error statistic  p.value conf.low conf.high\n  <chr>                   <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)             4.47    0.0874     17.1   8.04e-66    3.77      5.31 \n2 divisionCentral         1.01    0.0299      0.441 6.59e- 1    0.956     1.07 \n3 divisionMetropolitan    0.977   0.0303     -0.756 4.50e- 1    0.921     1.04 \n4 divisionPacific         0.964   0.0305     -1.20  2.29e- 1    0.908     1.02 \n5 is_home                 1.09    0.0215      3.80  1.44e- 4    1.04      1.13 \n6 avg_dist                0.989   0.00239    -4.68  2.88e- 6    0.984     0.994\n```\n\n\n:::\n:::\n\n\n. . .\n\nOne foot of average shot distance further from the net is associated with the mean number of goals being multiplied by 0.988 [95% CI(0.984, 0.993)].\n\nThe expected number of goals changes (is multiplied) by a factor of 1.085 (95% CI [1.04, 1.13]) if the team is home in comparison to away teams, after accounting for shot distance and division.\n\n## Deviance test \n\nOften used for testing null that\n  \n  - a relationship is linear rather than quadratic or cubic\n  - a continuous predictor’s relationship with the response is identical regardless of the level of a factor predictor with several levels\n  - simply testing null that several specific predictors are not associated with the response\n\nThe deviance difference is a likelihood ratio statistic. Likelihood ratio statistics are asymptotically chi-square, so this test has a chi-squared distribution.\n\n## Deviance test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_league <- glm(goals ~ division + is_home + avg_dist, family = \"poisson\", data = scoring)\nfit_simple <- glm(goals ~ is_home + avg_dist, family = \"poisson\", data = scoring)\n\nanova(fit_simple, fit_league, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: goals ~ is_home + avg_dist\nModel 2: goals ~ division + is_home + avg_dist\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1      2799     3162.6                     \n2      2796     3159.4  3   3.2622   0.3529\n```\n\n\n:::\n:::\n\n\nA deviance test comparing our model with a reduced model fit solely with average shot distance and home advantage **does not** provide evidence that division is associated with number of goals scored.  \n\n## Checking the assumptions\n\nPoisson regression makes 3 assumptions:\n\n1. The observations are conditionally independent, given $X$.\n\n  - Check with domain knowledge!\n  \n2. The response variable follows the poisson distribution.\n\n  - Check with a histogram (EDA)!\n  \n3. The mean of the response is related to the predictors through the chosen link function: we want a linear relationship between the predictor and the log of the outcome (either rate or count). \n\n- Check with empirical link plot in EDA or with residuals after fitting model.\n\n- Doesn't apply to factor variables\n  \n  - the model estimates a separate mean (or effect) for each category, so there is no underlying numeric scale on which a linear relationship could be assumed or violated.\n\n  \n## Checking the assumptions with an empirical link plot\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(regressinator)\n\nscoring |>\n  bin_by_quantile(avg_dist, breaks = 10) |>\n  summarize(\n    mean_avg_dist = mean(avg_dist),\n    log_goals = empirical_link(\n      goals,\n      family = poisson(link = \"log\"),\n    n = n()\n  )) |>\n  ggplot(aes(x = mean_avg_dist, y = log_goals)) +\n  geom_point()+\n  geom_smooth() +\n  labs(x = \"Avg shot distance\", y = \"Log goals\")\n```\n:::\n\n\n:::\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-glm_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n:::\n:::\n\n\n## Checking with randomized quantile residuals\n\nIn short, randomized quantile residuals deal with the patterns produced by discrete response variables by calculating the CDF for each observation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment_quantile(goals_poisson) %>%\n  ggplot(aes(x=avg_dist, y = .quantile.resid))+\n  geom_point(alpha=0.7)+\n  theme_bw(base_size = 22)+\n  labs(x=\"Shot distance\", y=\"Randomized quantile residual\")+\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](17-glm_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Model residuals and goodness-of-fit measures {visibility=\"hidden\"}\n\n*   Pearson residuals: $\\displaystyle r_i = \\frac{y_i-\\hat{\\lambda}_i}{\\sqrt{\\hat{\\lambda}_i}}$\n\n*   Deviance residuals: $\\displaystyle d_i = \\textrm{sign}(y_i-\\hat{\\lambda}_i) \\sqrt{2 \\left[y_i \\log\\left(\\frac{y_i}{\\hat{\\lambda}_i}\\right) -(y_i - \\hat{\\lambda}_i) \\right]}$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresiduals(goals_poisson, type = \"pearson\")\nresiduals(goals_poisson, type = \"deviance\")\n```\n:::\n\n\n*   Model summaries\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(goals_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n  null.deviance df.null logLik    AIC    BIC deviance df.residual  nobs\n          <dbl>   <int>  <dbl>  <dbl>  <dbl>    <dbl>       <int> <int>\n1         3204.    2801 -5494. 11000. 11036.    3159.        2796  2802\n```\n\n\n:::\n:::\n\n\n**As before, we prefer assessment in terms of out-of-sample/test set performances over these measures**\n\n## Poisson offset\n\n- The count of a particular unit might vary based on population or amount of time.\n\n. . . \n\n- Examples of when to use an offset\n\n  - modeling number of arrested insurrectionists by county (population offset)\n  \n  - counting bird species in varies forests (size of forest or time spent birding offset)\n  \n. . . \n\n- Why not just include this as a variable?\n  \n  - In the situations above, interpreting with counts doesn't make much sense\n\n  -  Including the variable as an offset constrains the model to predict rates rather than raw counts by fixing its coefficient to 1\n  \n## Poisson offset\n\nFor hockey data: should we include shots as a offset? Depends on what question you are trying to answer. \n\n  - Using shots as an offset: Do division, home ice, and average shot distance affect a team's goal-scoring rate per shot?\n  \n  - Using shots as a predictor: Holding division, home ice, and average shot distance constant, how does generating more shots affect expected goals?\n  \n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngoals_offset <- glm(goals ~ division + is_home + avg_dist, \n                 offset = log(shots), # include with coefficient 1\n                 data = scoring, family = poisson(link = \"log\"))\n\ntidy(goals_offset, exponentiate = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  term                 estimate std.error statistic   p.value\n  <chr>                   <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)            0.0694   0.0885    -30.1   1.12e-199\n2 divisionCentral        1.04     0.0299      1.22  2.22e-  1\n3 divisionMetropolitan   0.977    0.0303     -0.754 4.51e-  1\n4 divisionPacific        0.928    0.0305     -2.44  1.46e-  2\n5 is_home                1.03     0.0215      1.25  2.12e-  1\n6 avg_dist               0.993    0.00243    -2.87  4.12e-  3\n```\n\n\n:::\n:::\n\n\nA 10-foot increase in average shot distance is associated with approximately a $0.99306499^{10} = 0.933$ lower goal-scoring rate per shot, holding division and home ice constant.\n\n  \n## Overdispersion\n\n* Overdispersion is a common problem faced in Poisson regression when the variance is larger than what is assumed under the model\n\n. . .\n\n* Recall that a Poisson distribution assumes equidispersion (i.e. the mean and variance are equal)\n\n. . .\n\n* Any concerns here?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar(scoring$goals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.182643\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(scoring$goals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.109208\n```\n\n\n:::\n:::\n\n\n## Negative binomial regression\n\nKey idea: introduces another parameter such that the variance can exceed the mean\n\n. . .\n\nWe have $E(Y)  = \\lambda$ and $\\text{Var}(Y)=\\lambda(1+\\alpha \\lambda)$\n\n. . .\n\n* The variance is still proportional to $\\lambda$, but depends on the dispersion parameter $\\alpha \\ge 0$\n\n. . .\n\n* The further $\\alpha$ falls above 0, the greater the overdispersion relative to Poisson variability\n\n. . .\n\n* As $\\alpha$ decreases toward 0, the variance decreases toward $\\lambda$ , and the model converges to a Poisson distribution\n\n. . .\n\nSee [here](https://bookdown.org/roback/bookdown-BeyondMLR/ch-poissonreg.html#negative-binomial-modeling) for more information\n\n## Negative binomial regression\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngoals_nb <- MASS::glm.nb(goals ~ division + is_home + avg_dist, data = scoring)\nsummary(goals_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nMASS::glm.nb(formula = goals ~ division + is_home + avg_dist, \n    data = scoring, init.theta = 415.9359625, link = log)\n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           1.49745    0.08772  17.071  < 2e-16 ***\ndivisionCentral       0.01320    0.03004   0.440 0.660255    \ndivisionMetropolitan -0.02286    0.03039  -0.752 0.452029    \ndivisionPacific      -0.03669    0.03064  -1.197 0.231123    \nis_home               0.08185    0.02162   3.786 0.000153 ***\navg_dist             -0.01119    0.00240  -4.661 3.15e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(415.936) family taken to be 1)\n\n    Null deviance: 3182.3  on 2801  degrees of freedom\nResidual deviance: 3138.4  on 2796  degrees of freedom\nAIC: 11002\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  416 \n          Std. Err.:  1535 \nWarning while fitting theta: alternation limit reached \n\n 2 x log-likelihood:  -10987.88 \n```\n\n\n:::\n:::\n\n\n## Zero-inflated Poisson regression\n\n*   One common problem in modeling count data is the prevalence of zeros\n\n. . .\n\n*   While the Poisson distribution allows for zero counts, there are problems with a lot more zeros observed than expected for Poisson data\n\n. . .\n\n*   A **zero-inflated Poisson (ZIP) model** is a mixture model with two components\n\n    *   Logistic regression model to predict whether the response will be zero (whether 0 goals are observed) $$P(Y = 0) = \\pi + (1 - \\pi)e^{\\lambda}$$\n\n    *   Poisson regression model for non-zero counts (non-zero goal values) $$P(Y = y) = (1 - \\pi) \\frac{\\lambda^y e^{-\\lambda}}{y!}, \\text{\nfor } y = 1, 2, 3, \\dots$$\n\n\n## More on modeling with GLMs\n\n- GLMs are a big topic! We've only fully worked through an example of the poisson. Other response distributions follow similar ideas but have their own nuances. \n\n. . .\n\n- Binomial regression: used with binary outcomes where there is a fixed and known total number of trials. \n  - Each observation consists of a number of successes and a total number of trials; the number of trials may differ between observations\n\n. . .\n\n- Gamma regression:  Strictly positive, continuous data that are right-skewed, where the variance increases with the mean. \n\n  - Tweedie regression: Continuous data with a high density of exact zeros (e.g., insurance claim payouts where many people file $0, but some file large amounts).\n  \n. . .\n  \nFeel free to explore more or ask us questions!\n\n## Resources\n\n*   [Alex Reinhart's 36-707 Regression Analysis Notes on GLMs](https://www.refsmmat.com/courses/707/lecture-notes/response-distributions.html)\n\n* [Beyond Multiple Linear Regression: Paul Roback and Julie Legler](https://bookdown.org/roback/bookdown-BeyondMLR/)\n\n## Appendix: Code to build dataset\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhockey <- read_csv(\"https://raw.githubusercontent.com/36-SURE/2026/main/data/nhl-shots-2021.csv\")\nsummary <- hockey |>\n  group_by(game_id, event_team, home_name) |>\n  summarize(goals_home = max(home_score), goals_away = max(away_score), shots = n(), avg_dist = mean(shot_distance, na.rm=T), avg_angle = mean(shot_angle, na.rm=T)) |>\n  mutate(goals = case_when(home_name == event_team ~ goals_home, \n                           TRUE ~ goals_away), \n         is_home = case_when(event_team == home_name  ~ 1, \n                             TRUE ~ 0)) |>\n  dplyr::select(-goals_home, -goals_away, -home_name) |>\n  mutate(division = case_when(event_team %in% c(\"Boston Bruins\", \"Buffalo Sabres\", \"Detroit Red Wings\", \"Florida Panthers\", \"Montréal Canadiens\", \"Ottawa Senators\", \"Tampa Bay Lightning\", \"Toronto Maple Leafs\") ~ \"Atlantic\",\n                         event_team %in% c(\"Carolina Hurricanes\", \"Columbus Blue Jackets\", \"New Jersey Devils\", \"New York Islanders\", \"New York Rangers\", \"Philadelphia Flyers\", \"Pittsburgh Penguins\", \"Washington Capitals\" ) ~ \"Metropolitan\",\n                         event_team %in% c(\"Arizona Coyotes\",  \"Chicago Blackhawks\", \"Colorado Avalanche\", \"Dallas Stars\", \"Minnesota Wild\", \"Nashville Predators\", \"St. Louis Blues\", \"Winnipeg Jets\") ~ \"Central\",\n                         event_team %in% c(\"Anaheim Ducks\", \"Calgary Flames\", \"Edmonton Oilers\", \"Los Angeles Kings\", \"San Jose Sharks\", \"Seattle Kraken\", \"Vancouver Canucks\", \"Vegas Golden Knights\") ~ \"Pacific\"))\n```\n:::\n\n\n",
    "supporting": [
      "17-glm_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}