---
title: "Lectures"
---

Updated daily before lecture.


## Contents
 

|            | Date    | Title                                                     | Materials                                |
|------------|---------|-----------------------------------------------------------|------------------------------------------|
| Lecture 0  | June 1  | Welcome to CMSACamp 2026                                      | [slides](lectures/00-welcome.qmd)        |
| Lecture 1  | June 2  | Exploring data: into the `tidyverse`                      | [slides](lectures/01-explore.qmd)        |
| Lecture 2  | June 3  | Data visualization: the grammar of graphics and `ggplot2` | [slides](lectures/02-graphics.qmd)       |
| Lecture 3  | June 4  | Data visualization: categorical data                      | [slides](lectures/03-categorical.qmd)|
| Lecture 4  | June 5  | Data visualization: quantitative data                     | [slides](lectures/04-quantitative.qmd)   |
| Lecture 5  | June 8  | Data visualization: density estimation                    | [slides](lectures/05-density.qmd)        | 
| Lecture 6  | June 9 | Unsupervised learning: $k$-means clustering               | [slides](lectures/06-kmeans.qmd)         |
| Lecture 7  | June 10 | Unsupervised learning: hierarchical clustering            | [slides](lectures/07-hierarchical.qmd)   |
| Lecture 8  | June 11 | Unsupervised learning: Gaussian mixture models            | [slides](lectures/08-mixture.qmd)        |
| Lecture 9  | June 12 | Presentations                                             | [slides](lectures/09-presentation.qmd)   |
| Lecture 10 | June 15 | Supervised learning: model assessment vs selection        | [slides](lectures/10-tradeoffs.qmd)     |
| Lecture 11 | June 16 | Supervised learning: linear regression                    | [slides](lectures/11-linear.qmd)         |
| Lecture 12 | June 17 | Supervised learning: intro to variable selection | [slides](lectures/12-varsel.qmd)       |
| Lecture 13 | June 18 | Supervised learning: regularization                       | [slides](lectures/13-regularization.qmd) |
| Lecture 14 | June 22 | Dimension reduction: principal component analysis          | [slides](lectures/14-pca.qmd) |
| Lecture 15 | June 23 | Supervised learning: linear discriminant analysis                | [slides](lectures/15-lda.qmd)       |
| Lecture 16 | June 24 | Supervised learning: logistic regression                | [slides](lectures/16-logistic.qmd)       |
| Lecture 17 | June 25 | Supervised learning: generalized linear models            | [slides](lectures/17-glm.qmd)            |
| Lecture 18 | June 26 | Supervised learning: nonparametric regression                                | [slides](lectures/18-nonparametric.qmd)        |
| Lecture 19 | June 29  | Supervised learning: decision trees                       | [slides](lectures/19-trees.qmd)          |
| Lecture 20 | June 30  | Supervised learning: bagging and boosting                 | [slides](lectures/20-ensemble.qmd)       |
| Lecture 21 | July 1 |  Advanced topics: factor analysis    | [slides](lectures/21-fa.qmd)        |
| Lecture 22 | July 6 |  Advanced topics: survival analysis  | [slides](lectures/22-survival.qmd)     |
| Lecture 23 | July 7 |  Advanced topics: mixed effects  | [slides](lectures/23-mixed.qmd)        |
| Lecture 24 | July 8 |  Advanced topics: SQL | [slides](lectures/24-sql.qmd)        |
<!--
| Lecture 22 | July 9  | Building a website with Quarto                            | [slides](lectures/22-website.qmd)        | -->


<!--

| Lecture 21 | XXXXXXX | Supervised learning: multinomial classification           | [slides](lectures/21-multinomial.qmd)    |

-->

## Guest lectures

* Tracking data, part 1 [slides](https://bdbowel.netlify.app)
