---
title: "Pittsburgh-based Resources"
toc: true
---

## CMU Sponsored ID

A [CMU sponsored ID](https://www.cmu.edu/idplus/idcards/sponsored.html) is an optional, additional expense for students that can provide the following:

* General building access

* Fitness center access (GroupX classes not included)

* Library access & borrowing of books

* CMU campus shuttles & escort services

  * Note that Pittsburgh Bus Transit is not included

## Pittsburgh Bus/Transit Pass

If you would like to use public transit to explore what Pittsburgh has to offer, please see the below links for more information:

* [Current bus fares](https://www.rideprt.org/fares-and-passes/fare-information/)

* [Getting a bus/fare pass](https://www.rideprt.org/fares-and-passes/)

* Personally, we recommend [Google Maps](https://www.google.com/maps/place/4805+Frew+St,+Pittsburgh,+PA+15213/@40.4418248,-79.9473227,17z/data=!3m1!4b1!4m6!3m5!1s0x8834f220cd547121:0xa666c0a7f69a9d18!8m2!3d40.4418248!4d-79.9473227!16s%2Fg%2F11ggb931pl?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D) (for planning routes) and the [Transit App](https://transitapp.com/) (for real-time tracking) to coordinate bus plans.

## Medical/Wellness Resources

If you find yourself in need of physical, mental, or emotional attention, please utilize these local institutions for assistance:

* [UPMC Urgent Care Shadyside](https://providers.upmc.com/provider/upmc-urgent-care-shadyside/1998692) 

  * 5231 Centre Ave, Pittsburgh, PA 15232
  
  * 412-623-4114
  
* [UPMC Presbyterian Hospital](https://www.upmc.com/locations/hospitals/presbyterian?utm_source=google&utm_campaign=business-profile&utm_content=upmcpresbyterian-pittsburgh-website)

  * 200 Lothrop St, Pittsburgh, PA 15213
  
  * 412-755-2307
  
* [Allegheny Health Network Emergency Care Brentwood](https://ahnneighborhood.org/locations/brentwood/)

  * 3290 Saw Mill Run Blvd, Brentwood, PA 15227
  
*  [Resolve Crisis Services](https://www.upmc.com/services/behavioral-health/programs/emergency-crisis/resolve-crisis-services)

  * 333 North Braddock Ave, Pittsburgh, PA 15213
  
  * 1-888-796-8226
  
* [Allies for Health and Well-Being](https://www.lgbtq.pitt.edu/find-support/local-resources)

  * Medical support and community-based resources for individuals living with or at risk for HIV, viral hepatitis, and other sexually transmitted infections
  
  * Local support and resources for members of the LGBTQ+ community

## Food Insecurity

If you find yourself struggling with having enough food to get through your time here, please contact the following resource for assistance:

* [Greater Pittsburgh Community Food Bank](https://pittsburghfoodbank.org/find-food/get-help/) 412-460-3663 ext. 655

## Finding a Faith Community

If you are part of a religious community and want to find a local community during your time here, please use the following resource to find a faith community:

* [CMU Council of Religious Advisors](https://www.cmu.edu/wellbeing/about-us/cora.html)