---
title: "Activities To Do in Pittsburgh"
toc: true
---

## Sports

Pittsburgh sports are very fun to attend (regardless of how well the teams may or may not be doing in their respective seasons...)

* [Pittsburgh Pirates (MLB)](https://www.mlb.com/pirates)

* [Pittsburgh Riverhounds SC](https://www.riverhounds.com)

## Nature

* [Phipps Conservatory](https://www.phipps.conservatory.org/)

* [Schenley Park](https://pittsburghparks.org/explore-your-parks/regional-parks/schenley-park/)

  * 456 acres, very close to campus

  * Walking/running trails
  
  * Public pool ($5 cash entry for adults)

* [Frick Park](https://pittsburghparks.org/explore-your-parks/regional-parks/frick-park/)

  * 644 acres, in Point Breeze/Squirrel Hill

  * Lots of walking/running trails (beware of the hills!)

* [Three Rivers Heritage Trail](https://friendsoftheriverfront.org/three-rivers-heritage-trail/)

  * 35-mile paved trail walking/running/biking
  
  * Accessible from various points around the city, such as at the [Eliza Furnace Trail Entrance](https://www.google.com/maps/place/Eliza+Furnace+Trail+Entrance/@40.4325004,-79.9623889,17.26z/data=!4m6!3m5!1s0x8834f182f2646fb3:0xf607d394a4b492a3!8m2!3d40.4329431!4d-79.9624014!16s%2Fg%2F1vy7h6_q?entry=ttu&g_ep=EgoyMDI2MDUyNy4wIKXMDSoASAFQAw%3D%3D)

* [North Park](https://www.alleghenycounty.us/Parks-and-Events/Parks/North-Park)

  * Lake with kayaks, stand-up paddleboards, etc. available to rent

## Culture

* [Carnegie Library](https://www.carnegielibrary.org/)

  * A whole network of libraries across the city, but it’s main location is at the Museum on Forbes St.
  
* [Carnegie Museums](https://carnegiemuseums.org/)

  * [Carnegie Museum of Art](https://carnegiemuseums.org/our-museums/carnegie-museum-of-art/) and [Museum of Natural History](https://carnegiemuseums.org/our-museums/carnegie-museum-of-natural-history/) are right by campus, on Forbes St.
  
  * [Kamin Science Center](https://carnegiemuseums.org/our-museums/kamin-science-center/) and [The Andy Warhol Museum](https://carnegiemuseums.org/our-museums/the-andy-warhol-museum/) are both in North Shore (near PNC Park).

* [Summer Festivals](https://www.visitpittsburgh.com/events-festivals/annual-events/#jlsummer-events)

  * Includes Pogopalooza, Picklesburgh (very popular), Pittsburgh Vintage Grand Prix Motorsport Festival, and more! 
  
* [Pittsburgh Zoo and Aquarium](https://www.pittsburghzoo.org)


* [Pittsburgh Outdoor Movies](https://www.pittsburghpa.gov/Recreation-Events/Events/Dollar-Bank-Cinema-In-The-Park)


## Food

A non-exhaustive list of some good food options:

* Pamela's P&G Diner

* Pigeon Bagels

* The Porch

* Kiin Lao & Thai Eatery

* Taiwanese Bistro Cafe 33

* KuJiRa Sushi & Bar

* Iron Born Pizza

* East End Brewery
 
* [Farmers Markets](https://www.visitpittsburgh.com/restaurants-culinary/farms-farmers-markets/guide-to-pittsburgh-farmers-markets/)

*On/near campus:*

  * [S. Craig St.](https://share.google/0W1gegJFGr4VXYuc9): Chipotle, Ali Baba, Rose Tea Café, Union Grill, Sushi Fuku, and EatUnique
  
  * [Campus dining](https://apps.studentaffairs.cmu.edu/dining/conceptinfo/)



## Neighborhoods

* [Downtown](https://downtownpittsburgh.com/)

* [Lawrenceville (Butler St.)](https://www.visitpittsburgh.com/blog/lawrenceville/)

* [Shadyside (Walnut St.)](https://www.visitpittsburgh.com/blog/discovering-shadyside/)

* [Squirrel Hill (Forbes/Murray Ave.)](https://www.visitpittsburgh.com/neighborhoods/squirrel-hill/)

* [Strip District](https://www.visitpittsburgh.com/neighborhoods/strip-district/)

* [South Side](https://www.visitpittsburgh.com/neighborhoods/south-side/) 


