<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content=" CMSACamp 2026 Department of Statistics &amp; Data Science Carnegie Mellon University">

<title>Supervised learning: linear regression – CMSACamp 2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../icon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cf27875dd1ae9327fe69e76602a4a4de.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">CMSACamp 2026</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lectures.html"> 
<span class="menu-text">Lectures</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../labs.html"> 
<span class="menu-text">Labs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../bios.html"> 
<span class="menu-text">Bios</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../r-setup.html"> 
<span class="menu-text">R and RStudio Setup</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../git-setup.html"> 
<span class="menu-text">Git and GitHub Setup</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="11-linear.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Supervised learning: linear regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><br>CMSACamp 2026<br><br>Department of Statistics &amp; Data Science<br>Carnegie Mellon University </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="background" class="level1">
<h1>Background</h1>
<section id="recap-supervised-learning" class="level2">
<h2 class="anchored" data-anchor-id="recap-supervised-learning">Recap: supervised learning</h2>
<p><strong>Goal</strong>: uncover associations between a set of <em>predictor</em> (i.e, <em>independent</em>/<em>explanatory</em>) variables/features and a single <em>response</em> (i.e., <em>dependent</em>) variable</p>
<ul>
<li><p><strong>Prediction</strong>: Accurately predict unseen test cases</p></li>
<li><p><strong>Inference</strong>: Understand which features affect the response (and how)</p></li>
</ul>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple linear regression</h2>
<p>Assume a <strong>linear relationship</strong> between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[
Y_{i}=\beta_{0}+\beta_{1} X_{i}+\epsilon_{i}, \quad \text { for } i=1,2, \dots, n,
\]</span></p>
<div class="fragment">
<p><em>where:</em></p>
<ul>
<li><p><span class="math inline">\(Y_i\)</span> is the <span class="math inline">\(i\)</span>th value for the <strong>response</strong> variable</p></li>
<li><p><span class="math inline">\(X_i\)</span> is the <span class="math inline">\(i\)</span>th value for the <strong>predictor</strong> variable</p></li>
</ul>
<p><em>and</em></p>
</div>
<div class="incremental">
<ul class="incremental">
<li><p><span class="math inline">\(\beta_0\)</span> is an <em>unknown</em>, constant <strong>intercept</strong>: average value for <span class="math inline">\(Y\)</span> if <span class="math inline">\(X = 0\)</span> (<em>be careful sometimes…</em>)</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> is an <em>unknown</em>, constant <strong>slope</strong>: change in average value for <span class="math inline">\(Y\)</span> associated with a one-unit increase in <span class="math inline">\(X\)</span></p></li>
<li><p><span class="math inline">\(\epsilon_i\)</span> is the <strong>random</strong> noise: assume <strong>independent, identically distributed</strong> (<em>iid</em>) from a normal distribution</p>
<ul class="incremental">
<li>That is, <span class="math inline">\(\displaystyle \epsilon_i \overset{iid}{\sim}N(0, \sigma^2)\)</span> with constant variance <span class="math inline">\(\sigma^2\)</span></li>
</ul></li>
</ul>
</div>
</section>
<section id="simple-linear-regression-estimation" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-estimation">Simple linear regression estimation</h2>
<p>We are estimating the <strong>conditional expectation (mean)</strong> for <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[\mathbb{E}[Y_i \mid X_i] = \beta_0 + \beta_1X_i\]</span></p>
<p>. . .</p>
<p>How do we estimate the <strong>best fitted</strong> line (i.e., how do we estimate <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>)?</p>
<p>. . .</p>
<p><strong>Ordinary least squares (OLS)</strong> - by minimizing the <strong>residual sum of squares (RSS)</strong></p>
<p><span class="math display">\[\text{RSS} \left(\beta_{0}, \beta_{1}\right)=\sum_{i=1}^{n}\left[Y_{i}-\left(\beta_{0}+\beta_{1} X_{i}\right)\right]^{2}=\sum_{i=1}^{n}\left(Y_{i}-\beta_{0}-\beta_{1} X_{i}\right)^{2}\]</span></p>
<p>. . .</p>
<p><span class="math display">\[
\displaystyle
\widehat{\beta}_{1}=\frac{\sum_{i=1}^{n}\left(X_{i}-\bar{X}\right)\left(Y_{i}-\bar{Y}\right)}{\sum_{i=1}^{n}\left(X_{i}-\bar{X}\right)^{2}} \quad \text{ and } \quad \widehat{\beta}_{0}=\bar{Y}-\widehat{\beta}_{1} \bar{X},
\]</span></p>
<p>where <span class="math inline">\(\displaystyle \bar{X} = \frac{1}{n}\sum_{i=1}^n X_i\)</span> and <span class="math inline">\(\displaystyle \bar{Y} = \frac{1}{n}\sum_{i=1}^n Y_i\)</span></p>
</section>
<section id="visual-explanation" class="level2">
<h2 class="anchored" data-anchor-id="visual-explanation">Visual explanation</h2>
<p>Imagine a 2D scatterplot with different data points</p>
<ul>
<li><p>Linear regression aims to find a “best fit” line that minimizes the vertical distance between the line and the data points</p></li>
<li><p>The vertical distance is known as a <strong>residual</strong> (difference between the actual y-value of a data point and the predicted y-value on the regression line)</p></li>
</ul>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="linear-regression-in-r" class="level1 page-columns page-full">
<h1>Linear regression in <code>R</code></h1>
<section id="example-data-nfl-teams-summary" class="level2">
<h2 class="anchored" data-anchor-id="example-data-nfl-teams-summary">Example data: NFL teams summary</h2>
<p>Dataset created from <code>nflfastR</code>, summarizing NFL team performances from 1999 to 2020</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_light</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"http://www.stat.cmu.edu/cmsac/sure/2021/materials/data/regression_projects/nfl_team_season_summary.csv"</span>) <span class="co"># throwback using CMSACamp 2021/2022 data</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(nfl_teams_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 701
Columns: 55
$ season                          &lt;dbl&gt; 1999, 1999, 1999, 1999, 1999, 1999, 19…
$ team                            &lt;chr&gt; "ARI", "ATL", "BAL", "BUF", "CAR", "CH…
$ offense_completion_percentage   &lt;dbl&gt; 0.4774624, 0.5036630, 0.4520796, 0.540…
$ offense_total_yards_gained_pass &lt;dbl&gt; 2796, 3317, 2805, 3275, 4144, 4090, 31…
$ offense_total_yards_gained_run  &lt;dbl&gt; 1209, 1176, 1663, 2038, 1484, 1359, 19…
$ offense_ave_yards_gained_pass   &lt;dbl&gt; 4.667780, 6.075092, 5.072333, 6.167608…
$ offense_ave_yards_gained_run    &lt;dbl&gt; 3.148438, 3.195652, 4.126551, 4.125506…
$ offense_total_air_yards         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ offense_ave_air_yards           &lt;dbl&gt; NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN…
$ offense_total_yac               &lt;dbl&gt; 0, 11, 0, 161, 89, 508, 0, 35, 0, 9, 1…
$ offense_ave_yac                 &lt;dbl&gt; NaN, 11.000000, NaN, 3.926829, 4.45000…
$ offense_n_plays_pass            &lt;dbl&gt; 599, 546, 553, 531, 620, 711, 592, 546…
$ offense_n_plays_run             &lt;dbl&gt; 384, 368, 403, 494, 346, 383, 426, 311…
$ offense_n_interceptions         &lt;dbl&gt; 28, 18, 18, 14, 14, 20, 18, 14, 12, 18…
$ offense_n_fumbles_lost_pass     &lt;dbl&gt; 4, 7, 9, 5, 7, 9, 5, 5, 3, 4, 2, 7, 6,…
$ offense_n_fumbles_lost_run      &lt;dbl&gt; 5, 6, 2, 6, 7, 5, 3, 3, 7, 5, 4, 5, 5,…
$ offense_total_epa_pass          &lt;dbl&gt; -121.973897, -27.666629, -97.077660, 2…
$ offense_total_epa_run           &lt;dbl&gt; -71.171545, -78.883173, -35.461130, -4…
$ offense_ave_epa_pass            &lt;dbl&gt; -0.203629210, -0.050671482, -0.1755473…
$ offense_ave_epa_run             &lt;dbl&gt; -0.18534257, -0.21435645, -0.08799288,…
$ offense_total_wpa_pass          &lt;dbl&gt; -3.5184215, -1.9364824, -2.4247775, -0…
$ offense_total_wpa_run           &lt;dbl&gt; -2.2340416, -1.9415577, -1.5489192, -0…
$ offense_ave_wpa_pass            &lt;dbl&gt; -0.0058738256, -0.0035466711, -0.00438…
$ offense_ave_wpa_run             &lt;dbl&gt; -0.0058178167, -0.0052759719, -0.00384…
$ offense_success_rate_pass       &lt;dbl&gt; 0.3589316, 0.4029304, 0.3435805, 0.431…
$ offense_success_rate_run        &lt;dbl&gt; 0.3437500, 0.3288043, 0.3697270, 0.370…
$ defense_completion_percentage   &lt;dbl&gt; 0.5572519, 0.5410822, 0.4949153, 0.497…
$ defense_total_yards_gained_pass &lt;dbl&gt; 3143, 3129, 2647, 2669, 3519, 3793, 37…
$ defense_total_yards_gained_run  &lt;dbl&gt; 2258, 2057, 1112, 1342, 1871, 1833, 16…
$ defense_ave_yards_gained_pass   &lt;dbl&gt; 5.998092, 6.270541, 4.486441, 4.951763…
$ defense_ave_yards_gained_run    &lt;dbl&gt; 4.350674, 4.285417, 3.132394, 3.414758…
$ defense_total_air_yards         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ defense_ave_air_yards           &lt;dbl&gt; NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN…
$ defense_total_yac               &lt;dbl&gt; 0, 0, 0, 182, 103, 404, 0, 8, 0, 0, 17…
$ defense_ave_yac                 &lt;dbl&gt; 0.000000, NaN, NaN, 5.055556, 6.058824…
$ defense_n_plays_pass            &lt;dbl&gt; 524, 499, 590, 539, 588, 612, 553, 546…
$ defense_n_plays_run             &lt;dbl&gt; 519, 480, 355, 393, 430, 416, 442, 584…
$ defense_n_interceptions         &lt;dbl&gt; 17, 11, 19, 12, 15, 14, 12, 8, 23, 15,…
$ defense_n_fumbles_lost_pass     &lt;dbl&gt; 5, 1, 4, 4, 8, 7, 4, 6, 3, 5, 8, 2, 6,…
$ defense_n_fumbles_lost_run      &lt;dbl&gt; 3, 4, 1, 5, 1, 7, 8, 5, 5, 3, 7, 8, 5,…
$ defense_total_epa_pass          &lt;dbl&gt; -8.645207, 25.421303, -101.968213, -82…
$ defense_total_epa_run           &lt;dbl&gt; 4.927997, -22.014322, -61.295384, -70.…
$ defense_ave_epa_pass            &lt;dbl&gt; -0.016498487, 0.050944496, -0.17282747…
$ defense_ave_epa_run             &lt;dbl&gt; 0.009495177, -0.045863171, -0.17266305…
$ defense_total_wpa_pass          &lt;dbl&gt; -2.31819156, -0.35453726, -1.72091652,…
$ defense_total_wpa_run           &lt;dbl&gt; -0.2788802, -0.8169649, -2.1147486, -1…
$ defense_ave_wpa_pass            &lt;dbl&gt; -0.0044240297, -0.0007104955, -0.00291…
$ defense_ave_wpa_run             &lt;dbl&gt; -0.0005373414, -0.0017020102, -0.00595…
$ defense_success_rate_pass       &lt;dbl&gt; 0.4217557, 0.4028056, 0.3576271, 0.352…
$ defense_success_rate_run        &lt;dbl&gt; 0.4142582, 0.3812500, 0.3183099, 0.320…
$ points_scored                   &lt;dbl&gt; 245, 285, 324, 320, 421, 272, 283, 217…
$ points_allowed                  &lt;dbl&gt; 382, 380, 277, 229, 381, 341, 460, 437…
$ wins                            &lt;dbl&gt; 6, 5, 8, 11, 8, 6, 4, 2, 8, 6, 8, 8, 1…
$ losses                          &lt;dbl&gt; 10, 11, 8, 5, 8, 10, 12, 14, 8, 10, 8,…
$ ties                            &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
</div>
</section>
<section id="modeling-nfl-score-differential" class="level2">
<h2 class="anchored" data-anchor-id="modeling-nfl-score-differential">Modeling NFL score differential</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<p>Interested in modeling a team’s <strong>score differential</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="ot">&lt;-</span> nfl_teams_data <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">score_diff =</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>           points_scored <span class="sc">-</span> points_allowed)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> score_diff)) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"darkblue"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Score differential"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="relationship-between-score-differential-and-passing-performance" class="level2">
<h2 class="anchored" data-anchor-id="relationship-between-score-differential-and-passing-performance">Relationship between score differential and passing performance</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<p><code>offense_ave_epa_pass</code> is the team’s average expected points added (EPA) per pass attempt</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> offense_ave_epa_pass,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> score_diff)) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"EPA gained per pass attempt"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Score differential"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We fit linear regression models using <code>lm()</code>, formula is input as: <code>response ~ predictor</code></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>simple_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(score_diff <span class="sc">~</span> offense_ave_epa_pass, <span class="at">data =</span> nfl_teams_data) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="model-summary-using-summary" class="level2">
<h2 class="anchored" data-anchor-id="model-summary-using-summary">Model summary using <code>summary()</code></h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score_diff ~ offense_ave_epa_pass, data = nfl_teams_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-182.611  -46.600   -1.326   44.123  233.640 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            -4.890      2.561  -1.909   0.0566 .  
offense_ave_epa_pass  566.352     19.226  29.458   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 67.67 on 699 degrees of freedom
Multiple R-squared:  0.5539,    Adjusted R-squared:  0.5532 
F-statistic: 867.8 on 1 and 699 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="how-do-we-read-the-summary-output" class="level2">
<h2 class="anchored" data-anchor-id="how-do-we-read-the-summary-output">How do we read the <code>summary()</code> output?</h2>
<p>Our model is: <span class="math inline">\(\displaystyle \text{Score differential} = \beta_0 + \beta_1 \cdot \ (\text{Passing performance}) + \epsilon\)</span></p>
<p><strong>Under coefficients:</strong></p>
<ul>
<li><code>Estimate</code> are the model coefficient estimates: <span class="math inline">\(\displaystyle \hat{\beta}_0 = -4.89\)</span> and <span class="math inline">\(\hat{\beta}_1 = 566.35\)</span></li>
</ul>
<p>. . .</p>
<ul>
<li><code>Std. Error</code> is the <strong>standard errors</strong> for the coefficient estimates: <span class="math inline">\(\displaystyle \widehat{SE}(\hat{\beta}_0) = 2.56\)</span> and <span class="math inline">\(\displaystyle \widehat{SE}(\hat{\beta}_1) = 19.22\)</span></li>
</ul>
<p>. . .</p>
<ul>
<li><code>t value</code> are the test statistics (using a <a href="https://en.wikipedia.org/wiki/Student%27s_t-test">t-test</a>). For <span class="math inline">\(\beta_1\)</span>:</li>
</ul>
<p><span class="math display">\[
t = \frac{\hat{\beta}_1}{\widehat{SE}(\hat{\beta}_1)} = \frac{566.352}{19.22} = 29.45
\]</span></p>
<p><em>This tests whether there is a linear relationship between the predictor and the response, <span class="math inline">\(H_0: \beta_1 = 0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \beta_1 \neq 0\)</span>.</em></p>
</section>
<section id="inference-hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="inference-hypothesis-testing">Inference: hypothesis testing</h2>
<ul>
<li>Under the null hypothesis, <span class="math inline">\(H_0: \beta_1 = 0\)</span>, our test statistic <span class="math inline">\(t\)</span> follows a <span class="math inline">\(t\)</span>-distribution</li>
</ul>
<p>. . .</p>
<ul>
<li><p>To fully characterize a <span class="math inline">\(t\)</span>-distribution, we need the <a href="https://en.wikipedia.org/wiki/Degrees_of_freedom_(statistics)#In_linear_models"><strong>degrees of freedom</strong></a></p>
<ul>
<li><p>For linear regression, the degrees of freedom is <span class="math inline">\(n - (p + 1)\)</span> (where <span class="math inline">\(n\)</span> is the number of observations used to fit the model and <span class="math inline">\(p\)</span> is the number of estimated coefficients beyond the intercept)</p></li>
<li><p><code>summary()</code> tells us the degrees of freedom is <span class="math inline">\(699\)</span> (as <span class="math inline">\(701 - 2 = 699\)</span>)</p></li>
</ul></li>
</ul>
<p>. . .</p>
<ul>
<li><p><code>Pr(&gt;|t|)</code> is the <strong>p-value</strong>: probability of observing a value as extreme as the observed test statistic <em>under the null hypothesis</em></p>
<ul>
<li><span class="math inline">\(p\)</span>-value <span class="math inline">\(&lt; \alpha = 0.05\)</span> (conventional threshold): <strong>sufficient evidence to reject the null hypothesis that the coefficient is zero</strong></li>
</ul></li>
</ul>
<p>. . .</p>
<blockquote class="blockquote">
<p><em>In context:</em> For NFL teams, there was a statistically significant association between passing performance, as measured through the team’s average expected points added (EPA) per pass attempt, and season score differential, <span class="math inline">\(\hat{\beta} = 566.35\)</span>, <span class="math inline">\(t(699) = 29.45\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>.</p>
</blockquote>
</section>
<section id="inference-interpreting-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="inference-interpreting-coefficients">Inference: interpreting coefficients</h2>
<p>Since <code>offense_ave_epa_pass</code> is a quantitative predictor, we can interpret it as follows:</p>
<blockquote class="blockquote">
<p>For NFL teams, a one-unit increase in average expected points added (EPA) per pass attempt is associated with a 566.35 point increase in season score differential, on average (95% CI [528.60, 604.10]).</p>
</blockquote>
<p>. . .</p>
<ul>
<li><p>Always make sure to interpret important coefficients in context (<em>and with units when possible</em>)!</p></li>
<li><p>We can compute the <span class="math inline">\(95\%\)</span> confidence interval (CI) by doing <span class="math inline">\(\hat{\beta}_1 \pm 1.96 \cdot \widehat{SE}(\hat{\beta}_1)\)</span>, or using the <code>confint()</code> function:</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(simple_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %     97.5 %
(Intercept)           -9.919107   0.138374
offense_ave_epa_pass 528.604817 604.100144</code></pre>
</div>
</div>
</section>
<section id="model-summary-using-the-broom-package" class="level2">
<h2 class="anchored" data-anchor-id="model-summary-using-the-broom-package">Model summary using the <a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html"><code>broom</code></a> package</h2>
<p><code>glance()</code>: summary metrics of a model fit</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(simple_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.554         0.553  67.7      868. 1.26e-124     1 -3948. 7902. 7916.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p><code>tidy()</code>: coefficients table in a tidy format</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(simple_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term                 estimate std.error statistic   p.value
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             -4.89      2.56     -1.91 5.66e-  2
2 offense_ave_epa_pass   566.       19.2      29.5  1.26e-124</code></pre>
</div>
</div>
</section>
<section id="confidence-interval-for-model-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-model-coefficients">Confidence interval for model coefficients</h2>
<p>With <code>tidy()</code>, we can also obtain confidence intervals for each coefficient:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(simple_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term                 estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             -4.89      2.56     -1.91 5.66e-  2    -9.92     0.138
2 offense_ave_epa_pass   566.       19.2      29.5  1.26e-124   529.     604.   </code></pre>
</div>
</div>
<p>. . .</p>
<p><br></p>
<p>Another common interpretation of confidence intervals is the following (in context of <code>offense_ave_epa_pass</code>):</p>
<blockquote class="blockquote">
<p>We’re 95% confident that a one-unit increase in average expected points added (EPA) per pass attempt is associated with an increase of between 529 and 604 points in the season score differential for NFL teams, on average.</p>
</blockquote>
</section>
<section id="coefficient-of-determination" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-of-determination">Coefficient of determination</h2>
<p>The coefficient of determination (<span class="math inline">\(R^2\)</span>) estimates the <strong>proportion of the variance</strong> in <span class="math inline">\(Y\)</span> that is explained by <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[
\displaystyle R^2 = \frac{\text{var}(\hat{Y})}{\text{var}(Y)}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(<span class="fu">predict</span>(simple_lm)) <span class="sc">/</span> <span class="fu">var</span>(nfl_teams_data<span class="sc">$</span>score_diff) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5538537</code></pre>
</div>
</div>
<p>. . .</p>
<p>In linear regression, the square of the correlation coefficient is to be exactly the <strong>coefficient of determination</strong> (<span class="math inline">\(R^2\)</span>):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(nfl_teams_data<span class="sc">$</span>offense_ave_epa_pass, nfl_teams_data<span class="sc">$</span>score_diff)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5538537</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>55.4% of the variability in the season score differential can be explained by the linear relationship between season score differential and average expected points added (EPA) per pass attempt (the remaining 44.6% of the variation is due to other factors and/or noise).</p>
</blockquote>
</section>
<section id="generating-predictions" class="level2">
<h2 class="anchored" data-anchor-id="generating-predictions">Generating predictions</h2>
<p>We can use the <code>predict()</code> or <code>fitted()</code> function to get the fitted values from the regression model</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(simple_lm)) <span class="co"># also can input new data to predict()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6 
-120.21628  -33.58829 -104.31202   21.15045   57.18906  -23.34489 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">fitted</span>(simple_lm))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6 
-120.21628  -33.58829 -104.31202   21.15045   57.18906  -23.34489 </code></pre>
</div>
</div>
</section>
<section id="plot-observed-values-against-predictions" class="level2">
<h2 class="anchored" data-anchor-id="plot-observed-values-against-predictions">Plot observed values against predictions</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<p>Useful diagnostic (for <strong>any type of model</strong>, not just linear regression!)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(simple_lm)) <span class="sc">|&gt;</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pred, <span class="at">y =</span> score_diff)) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"orangered"</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">linewidth =</span> <span class="dv">2</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A “perfect” model will follow <strong>diagonal</strong></p>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="plot-observed-values-against-predictions-1" class="level2">
<h2 class="anchored" data-anchor-id="plot-observed-values-against-predictions-1">Plot observed values against predictions</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<p>Augment the data with model output using the <a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html"><code>broom</code> package</a></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="ot">&lt;-</span> simple_lm <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(nfl_teams_data) </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> score_diff)) <span class="sc">+</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"orangered"</span>, </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>augment()</code> adds various columns from model fit we can use in plotting for model diagnostics</p>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="assessing-assumptions-of-linear-regression" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="assessing-assumptions-of-linear-regression">Assessing assumptions of linear regression</h2>
<p>Recall that simple linear regression assumes that <span class="math inline">\(Y_i = \beta_0 + \beta_1  X_i + \epsilon_i\)</span>, with <span class="math inline">\(\epsilon_i \overset{iid}{\sim} N(0, \sigma^2)\)</span>.</p>
<p>. . .</p>
<p><br></p>
<p>Therefore, simple linear regression encodes <em>four</em> assumptions:</p>
<ul>
<li><p>The errors have mean zero (<em>linearity</em>): <span class="math inline">\(\mathbb{E}[\epsilon \mid X] = 0\)</span></p></li>
<li><p>The error variance is constant (<em>homoskedasticity</em>): <span class="math inline">\(\text{var}(\epsilon \mid X) = \sigma^2\)</span></p></li>
<li><p>The errors are independent: <span class="math inline">\(\text{var}(\epsilon \mid X) = \sigma^2\)</span> (<em>can be violated in different ways than homoskedasticity</em>)</p></li>
<li><p>The errors are normally distributed</p></li>
</ul>
<p>. . .</p>
<p><br></p>
<p>We’ve also assumed that <span class="math inline">\(X\)</span> is fixed, NOT random</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>For a helpful overview of regression assumptions and diagnostics, see <a href="https://www.refsmmat.com/courses/707/lecture-notes/regression-assumptions.html">Professor Alex Reinhart’s notes</a>.</p>
</div></div></section>
<section id="plot-residuals-against-fitted-values" class="level2">
<h2 class="anchored" data-anchor-id="plot-residuals-against-fitted-values">Plot residuals against fitted values</h2>
<p>Recall, the <strong>residual</strong> is the difference between the observed and fitted (predicted) values:</p>
<p><span class="math display">\[
\hat{\epsilon}_i = Y_i - \hat{Y}_i
\]</span></p>
<p>We can test several of the linear regression assumptions using the residuals</p>
<p>. . .</p>
<p><br></p>
<p>In particular using a <strong>residuals vs fitted values</strong> plot, we can:</p>
<ul>
<li><p>Assess linearity assumption: conditional the fitted values, do the residuals have mean zero?</p></li>
<li><p>Assess equal variance: across the fitted values, do the residuals have constant variance (<span class="math inline">\(\sigma^2\)</span>)?</p></li>
</ul>
<p>. . .</p>
<p><br></p>
<p><em>Note</em>: it is more difficult to assess the error independence and fixed <span class="math inline">\(X\)</span> assumptions. Ideally, these assumptions should be based on subject-matter knowledge</p>
</section>
<section id="plot-residuals-against-predicted-values" class="level2">
<h2 class="anchored" data-anchor-id="plot-residuals-against-predicted-values">Plot residuals against predicted values</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"orangered"</span>, <span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot the residual mean</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">fill =</span> <span class="st">"skyblue2"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><em>Two things to look for</em>:</p>
<ul>
<li><p>Any trend around horizontal reference line? <em>Violates linearity</em> (may have to additional covariates, polynomial terms, splines, etc.)</p></li>
<li><p>Unequal vertical spread? <em>Violates homoskedasticity</em> (consider using the <a href="https://sandwich.r-forge.r-project.org/articles/sandwich.html">sandwich estimator</a>)</p></li>
</ul>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="what-about-the-normality-assumption" class="level2">
<h2 class="anchored" data-anchor-id="what-about-the-normality-assumption">What about the normality assumption?</h2>
<div class="{columns}">
<div class="column">
<div class="incremental">
<ul class="incremental">
<li><p><strong>OLS doesn’t care about this assumption</strong>, it’s just estimating coefficients!</p></li>
<li><p>BUT in terms of inference, a violation of the normality of errors assumption:</p>
<ul class="incremental">
<li><p>May result in incorrect inferences in small samples</p></li>
<li><p>Usually does not have a big impact on inferences in larger samples (Weisberg 2014)</p></li>
</ul></li>
<li><p>We can detect whether the errors are (roughly) normally distributed by <strong>Q-Q plot</strong> on the <em>standardized residuals</em>, which are the residuals divided by their <a href="https://www.refsmmat.com/courses/707/lecture-notes/regression-geometry.html#least-squares-estimation">estimated standard deviation</a></p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\displaystyle \hat{\epsilon}_{\text{standardized}} = \frac{\hat{\epsilon}}{\hat{\sigma}}
\]</span></p>
</div>
</div>
</div>
<div class="column">
<div class="fragment">
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_data <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>(<span class="at">distribution =</span> stats<span class="sc">::</span>qnorm) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>(<span class="at">distribution =</span> stats<span class="sc">::</span>qnorm) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="linear-regression-with-one-categorical-predictor" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-with-one-categorical-predictor">Linear regression with one categorical predictor</h2>
<p>In this example, we look at three teams: Chicago Bears, Pittsburgh Steelers, and Seattle Seahawks</p>
<p>. . .</p>
<ul>
<li><p>We change the estimate and interpretation intercept of our regression line when we include a categorical variable (one level of the variable is “absorbed” into the itercept term)</p></li>
<li><p>Notice we only get two coefficients for the season besides the intercept: (i) <code>teamPIT</code> and (ii) <code>teamSEA</code></p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_subset <span class="ot">&lt;-</span> nfl_teams_data <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(team <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"PIT"</span>, <span class="st">"SEA"</span>, <span class="st">"CHI"</span>))</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>team_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(score_diff <span class="sc">~</span> team, <span class="at">data =</span> nfl_teams_subset)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(team_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    -11.6      17.0    -0.681 0.498      -45.6       22.4
2 teamPIT         83.2      24.1     3.46  0.000989    35.1      131. 
3 teamSEA         51.7      24.1     2.15  0.0357       3.57      99.8</code></pre>
</div>
</div>
</section>
<section id="linear-regression-with-one-categorical-predictor-1" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-with-one-categorical-predictor-1">Linear regression with one categorical predictor</h2>
<p>By default, <code>R</code> turns the categorical variables of <span class="math inline">\(m\)</span> levels (e.g.&nbsp;three teams) into <span class="math inline">\(m-1\)</span> indicator/binary variables for different categories relative to the baseline/reference level</p>
<ul>
<li><p>Indicator/binary variables are one if it is that level, and zero otherwise</p></li>
<li><p>By default, <code>R</code> uses alphabetical order to determine the reference level (<code>teamCHI</code> in this case)</p></li>
</ul>
<p>. . .</p>
<p><br></p>
<p>With our categorical predictor of team, our linear model is:</p>
<p><span class="math display">\[\widehat{\text{Score differential}} = -11.59 + 83.18 \ I_{\texttt{teamPIT}} + 51.68\ I_{\texttt{teamSEA}}\]</span></p>
</section>
<section id="linear-regression-with-one-categorical-predictor-2" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-with-one-categorical-predictor-2">Linear regression with one categorical predictor</h2>
<p><span class="math display">\[\widehat{\text{Score differential}} = -11.59 + 83.18 \ I_{\texttt{teamPIT}} + 51.68\ I_{\texttt{teamSEA}}\]</span></p>
<p>The intercept term gives us the (baseline) average y for the reference level</p>
<ul>
<li><em>In our context</em>: the expected season score differential for the Chicago Bears is <span class="math inline">\(-11.59\)</span> points (95% CI [<span class="math inline">\(-45.61\)</span>, <span class="math inline">\(22.43\)</span>])</li>
</ul>
<p>. . .</p>
<p>The coefficient estimates indicate the expected change in the response variable relative to the reference level</p>
<ul>
<li><em>For example</em>: the season score differential for the Pittsburgh Steelers is <span class="math inline">\(83.18\)</span> points higher (95% CI [<span class="math inline">\(35.07\)</span>, <span class="math inline">\(131.29\)</span>]) than than the season score differential for the Chicago Bears</li>
</ul>
</section>
<section id="comparing-observed-values-and-predictions" class="level2">
<h2 class="anchored" data-anchor-id="comparing-observed-values-and-predictions">Comparing observed values and predictions</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<ul>
<li><p>Similar to before, we can plot the actual and predicted ridership</p></li>
<li><p>To reiterate, all we’re doing is changing the intercept of our regression line by including a categorical variable</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_subset <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">team_pred =</span> <span class="fu">predict</span>(team_lm)) <span class="sc">|&gt;</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> score_diff, <span class="at">y =</span> team_pred)) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> team, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Actual score differential"</span>, </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted score differential"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="interactions" class="level2">
<h2 class="anchored" data-anchor-id="interactions">Interactions</h2>
<p>An interaction allows one predictor’s association with the outcome to depend on the value of another predictor</p>
<p>. . .</p>
<p><br></p>
<p><em>Example:</em> an interaction between <code>team</code> and <code>offense_ave_epa_pass</code> says that the association between passing performance and season score differential depends on the NFL team</p>
<p>. . .</p>
<p><br></p>
<p>In general, if we have a categorical and quantitative variables: we include an interaction term when believe associations between the quantitative variable and the response differ by category</p>
<p>. . .</p>
<p><br></p>
<p><em>This means those regression lines have different intercepts as well as different slopes</em></p>
</section>
<section id="visualizing-interactions" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-interactions">Visualizing interactions</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>nfl_teams_subset <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> offense_ave_epa_pass, <span class="at">y =</span> score_diff, <span class="at">color =</span> team)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  ggthemes<span class="sc">::</span><span class="fu">scale_color_colorblind</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpreting-interactions" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-interactions">Interpreting interactions</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>interaction_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(score_diff <span class="sc">~</span> offense_ave_epa_pass <span class="sc">*</span> team, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> nfl_teams_subset)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(interaction_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre style="font-size: 0.55em;"><code># A tibble: 6 × 5
  term                         estimate std.error statistic p.value
  &lt;chr&gt;                           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)                      7.82      18.2     0.431 0.668  
2 offense_ave_epa_pass           217.       138.      1.57  0.121  
3 teamPIT                         41.0       24.8     1.65  0.104  
4 teamSEA                         -8.91      23.5    -0.379 0.706  
5 offense_ave_epa_pass:teamPIT    98.3      199.      0.493 0.624  
6 offense_ave_epa_pass:teamSEA   592.       193.      3.07  0.00326</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{aligned}
{\text{Score differential}} = \beta_0 &amp;+ \beta_1 \ \text{Pass performance} + \beta_2 \ I_{\texttt{teamPIT}} + \beta_3 \ I_{\texttt{teamSEA}} \\
&amp;+ \beta_4 \{ \text{Pass performance} \times I_{\texttt{teamPIT}} \} +  \beta_5 \{ \text{Pass performance} \times I_{\texttt{teamSEA}} \}  + \epsilon \\
\end{aligned}
\]</span></p>
<p>. . .</p>
<p><em>Example interpretation</em> (comparing the Pittsburgh Steelers to the Chicago Bears):</p>
<blockquote class="blockquote">
<p>For the Chicago Bears, a one-unit increase in average expected points added (EPA) per pass attempt is associated with an increase of 216.70 points in season score differential, on average. But for the Pittsburgh Steelers, a one-unit increase in average expected points added (EPA) per pass attempt is associated with an increase of 216.70 + 98.28 = 314.98 points in season score differential, on average.</p>
</blockquote>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple linear regression</h2>
<p>We can include as many variables as we want (assuming that <span class="math inline">\(n &gt; p\)</span>):</p>
<p><span class="math display">\[Y=\beta_{0}+\beta_{1} X_{1}+\beta_{2} X_{2}+\cdots+\beta_{p} X_{p}+\epsilon\]</span></p>
<p>OLS estimates, <span class="math inline">\(\hat{\boldsymbol{\beta}} = (\hat{\beta}_{0}, \dots, \hat{\beta}_{p})'\)</span> in matrix notation (<span class="math inline">\(\boldsymbol{X}\)</span> is a <span class="math inline">\(n \times p\)</span> matrix):</p>
<p><span class="math display">\[\hat{\boldsymbol{\beta}} = (\boldsymbol{X} ^T \boldsymbol{X})^{-1}\boldsymbol{X}^T\boldsymbol{Y}\]</span></p>
<p>. . .</p>
<p>We can just add more variables to the formula in <code>R</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>multiple_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(score_diff <span class="sc">~</span> offense_ave_epa_pass <span class="sc">+</span> defense_ave_epa_pass, <span class="at">data =</span> nfl_teams_subset)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(multiple_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                 estimate std.error statistic  p.value
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)              12.3      4.97      2.47 1.62e- 2
2 offense_ave_epa_pass    443.      39.6      11.2  1.36e-16
3 defense_ave_epa_pass   -584.      52.0     -11.2  1.12e-16</code></pre>
</div>
</div>
</section>
<section id="multiple-linear-regression-1" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-1">Multiple linear regression</h2>
<p>Use adjusted <span class="math inline">\(R^2\)</span> when including multiple variables:</p>
<p><span class="math display">\[
\displaystyle R^2_{\text{adj}} = 1 - \frac{(1 - R^2)(n - 1)}{(n - p - 1)}
\]</span></p>
<ul>
<li><p>Adjusts for the number of regressors in the model (<span class="math inline">\(p\)</span>)</p></li>
<li><p>Adding more variables <strong>will always increase</strong> the model’s (unadjusted) <span class="math inline">\(R^2\)</span></p></li>
</ul>
<p>. . .</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(multiple_lm) <span class="co"># notice the diff. between unadj. and adj. R-squared</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.805         0.798  38.6      130. 4.61e-23     2  -333.  674.  683.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Also, recall <a href="https://en.wikipedia.org/wiki/Anscombe%27s_quartet">Anscombe’s quartet</a> and the <a href="https://en.wikipedia.org/wiki/Datasaurus_dozen">Datasaurus dozen</a>. In general, you should be cautious of any single number summary of an elusive concept like model “goodness”.</p>
</div></div></section>
<section id="regression-confidence-intervals-vs-prediction-intervals" class="level2">
<h2 class="anchored" data-anchor-id="regression-confidence-intervals-vs-prediction-intervals">Regression confidence intervals vs prediction intervals</h2>
<p>These answer different questions:</p>
<ol type="1">
<li><p>Do we want to predict the mean response for a particular value <span class="math inline">\(x^*\)</span> of the explanatory variable? <strong>Confidence interval</strong></p></li>
<li><p>Do we want to predict the response for an individual case? <strong>Prediction interval</strong></p></li>
</ol>
<p>. . .</p>
<p><em>Examples</em>:</p>
<ul>
<li><p>If we would like to know the average score differential for <strong>all</strong> NFL team-seasons with an average expected points added (EPA) per pass attempt of <span class="math inline">\(0.10\)</span>, then we would use an interval for the <strong>mean response</strong></p></li>
<li><p>If we want an intervalto contain the score differential <strong>a particular</strong> NFL team-season with with an average expected points added (EPA) per pass attempt of <span class="math inline">\(0.10\)</span>, then we need the interval for <strong>a single prediction</strong></p></li>
</ul>
</section>
<section id="regression-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="regression-confidence-intervals">Regression confidence intervals</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<p>The layer <code>geom_smooth()</code> displays <strong>confidence intervals</strong> for the regression line</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predict(simple_lm, interval = "confidence")</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>lm_plot <span class="ot">&lt;-</span> nfl_teams_subset <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> offense_ave_epa_pass, <span class="at">y =</span> score_diff)) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>lm_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<hr>
</section>
<section id="regression-confidence-intervals-1" class="level2">
<h2 class="anchored" data-anchor-id="regression-confidence-intervals-1">Regression confidence intervals</h2>
<p>Interval estimate for the MEAN response at a given observation (i.e.&nbsp;for the predicted AVERAGE <span class="math inline">\(\hat{\beta}_0 + \hat{\beta}_1 x^*\)</span>)</p>
<p>. . .</p>
<p><br></p>
<p>Based on standard errors for the estimated regression line at <span class="math inline">\(x^*\)</span>, we get that:</p>
<p><span class="math display">\[
SE_{\text{line}}\left(x^{*}\right)=\hat{\sigma} \cdot \sqrt{\frac{1}{n}+\frac{\left(x^{*}-\bar{x}\right)^{2}}{\sum_{i=1}^{n}\left(x_{i}-\bar{x}\right)^{2}}}
\]</span></p>
<p>. . .</p>
<p><br></p>
<p><em>Variation only comes from uncertainty in the parameter</em></p>
</section>
<section id="regression-prediction-intervals" class="level2">
<h2 class="anchored" data-anchor-id="regression-prediction-intervals">Regression prediction intervals</h2>
<p>Interval estimate for an INDIVIDUAL response at a given (new) observation</p>
<p>. . .</p>
<p><br></p>
<p>Must add the variance <span class="math inline">\(\sigma^2\)</span> of a <strong>single predicted value</strong>:</p>
<p><span class="math display">\[
SE_{\text{pred}}\left(x^{*}\right)=\hat{\sigma} \cdot \sqrt{1 + \frac{1}{n}+\frac{\left(x^{*}-\bar{x}\right)^{2}}{\sum_{i=1}^{n}\left(x_{i}-\bar{x}\right)^{2}}}
\]</span></p>
<p>. . .</p>
<p><br></p>
<p><em>Now, the variation comes from uncertainty in parameter estimates AND error variance</em></p>
</section>
<section id="confidence-intervals-versus-prediction-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-versus-prediction-intervals">Confidence intervals versus prediction intervals</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<ul>
<li><p>The standard error for predicting an individual response will always be larger than for predicting a mean response</p></li>
<li><p>Prediction intervals will always be wider than confidence intervals</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predict(simple_lm, interval = "prediction")</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>lm_plot <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> <span class="fu">augment</span>(simple_lm, <span class="at">interval =</span> <span class="st">"prediction"</span>),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">ymin =</span> .lower, <span class="at">ymax =</span> .upper),</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">fill =</span> <span class="cn">NA</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-linear_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>